In [ ]:
#| hide
from bqdf.core import *

# bqdf

> Ergonomic wrapper for pandas_gbq that simplifies loading BigQuery data into DataFramesa

This file will become your README and also the index of your documentation.

## Developer Guide

If you are new to using `nbdev` here are some useful pointers to get you started.

### Install bqdf in Development mode

```sh
# make sure bqdf package is installed in development mode
$ pip install -e .

# make changes under nbs/ directory
# ...

# compile to have changes apply to bqdf
$ nbdev_prepare
```

## Usage

### Installation

Install latest from the GitHub [repository][repo]:

```sh
$ pip install git+https://github.com/motdam/bqdf.git
```

or from [conda][conda]

```sh
$ conda install -c motdam bqdf
```

or from [pypi][pypi]


```sh
$ pip install bqdf
```


[repo]: https://github.com/motdam/bqdf
[docs]: https://motdam.github.io/bqdf/
[pypi]: https://pypi.org/project/bqdf/
[conda]: https://anaconda.org/motdam/bqdf

### Documentation

Documentation can be found hosted on this GitHub [repository][repo]'s [pages][docs]. Additionally you can find package manager specific guidelines on [conda][conda] and [pypi][pypi] respectively.

[repo]: https://github.com/motdam/bqdf
[docs]: https://motdam.github.io/bqdf/
[pypi]: https://pypi.org/project/bqdf/
[conda]: https://anaconda.org/motdam/bqdf

## How to use

This lib provides convenience functions for streamlining the interface of the pandas-gbq library to perform CRUD operations in BigQuery more quickly

In [ ]:
from google.oauth2 import service_account
import os
import json

In [ ]:

#| hide
import os
if 'CI' not in os.environ:  # CI is set automatically in GitHub Actions
    credentials = service_account.Credentials.from_service_account_info(
        json.loads(os.environ['GOOGLE_APPLICATION_CREDENTIALS'])
    )

In [ ]:

gn_query = """
-- top 10 girls names
SELECT name, sum(number) as name_count
 FROM `bigquery-public-data.usa_names.usa_1910_current` 
 where year = 2021
  and gender = 'F'
 group by all
 order by name_count desc
 LIMIT 10
"""

gn_query[:22]

'\n-- top 10 girls names'

### Reading a bq table

In [ ]:

df = read(gn_query, credentials=credentials, project_id='bq-sandbox-motdam')
df

Downloading:   0%|          |

Downloading: 100%|██████████|

Retrieved 10 rows × 2 cols in 0.55s
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     object
 1   name_count  10 non-null     Int64
dtypes: Int64(1), object(1)
memory usage: 302.0+ bytes
None

        name  name_count
0     Olivia       17728
1       Emma       15433
2  Charlotte       13285
3     Amelia       12952
4        Ava       12759

        name  name_count
0     Olivia       17728
1       Emma       15433
2  Charlotte       13285
3     Amelia       12952
4        Ava       12759
5     Sophia       12496
6   Isabella       11201
7        Mia       11096
8     Evelyn        9434
9     Harper        8388